apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iris
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    path: kustomize/iris
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: iris
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
    - CreateNamespace=true
