apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opensearch-project/opensearch-k8s-operator/tree/main/charts
    chart: opensearch-operator
    targetRevision: 2.12.0
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated: {}
